name: hilserl-torch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - absl-py=0.13.0=pyhd3eb1b0_0
  - anyio=3.5.0=py38h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=24.2.0=py38h06a4308_0
  - babel=2.11.0=py38h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_1
  - beautifulsoup4=4.12.3=py38h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotli=1.2.0=h27d5ac6_0
  - brotli-bin=1.2.0=h1421c7b_0
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - certifi=2024.8.30=py38h06a4308_0
  - cffi=1.17.1=py38h1fdaa30_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.1.7=py38h06a4308_0
  - cloudpickle=3.0.0=py38h06a4308_0
  - comm=0.2.1=py38h06a4308_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=h06a4308_1
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.4.1=hb982923_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.2=py38h5eee18b_0
  - dask-core=2023.4.1=py38h06a4308_0
  - debugpy=1.6.7=py38h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - ffmpeg=4.2.2=h20bf706_0
  - filelock=3.13.1=py38h06a4308_0
  - fonttools=4.51.0=py38h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - fsspec=2024.6.1=py38h06a4308_0
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py38h06a4308_0
  - importlib-metadata=7.0.1=py38h06a4308_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - importlib_resources=6.4.0=py38h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.29.5=py38h06a4308_0
  - ipython=8.12.2=py38h06a4308_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.19.1=py38h06a4308_0
  - jinja2=3.1.4=py38h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.23.0=py38h06a4308_0
  - jsonschema-specifications=2023.7.1=py38h06a4308_0
  - jupyter-packaging=0.7.12=pyhd3eb1b0_0
  - jupyter_client=8.6.0=py38h06a4308_0
  - jupyter_core=5.7.2=py38h06a4308_0
  - jupyter_server=1.23.4=py38h06a4308_0
  - jupyterlab=3.0.14=pyhd3eb1b0_1
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py38h06a4308_0
  - kiwisolver=1.4.4=py38h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb9589c4_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.2.0=h32cd6e7_0
  - libbrotlidec=1.2.0=ha2c5f68_0
  - libbrotlienc=1.2.0=h2e96acb_0
  - libcblas=3.9.0=12_linux64_mkl
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.22=h5eee18b_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=12_linux64_mkl
  - libnpp=12.2.5.30=0
  - libnvfatbin=12.4.127=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.50=h2ed474d_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtasn1=4.20.0=ha30cf84_0
  - libtiff=4.5.1=hffd6297_1
  - libunistring=0.9.10=h27cfd23_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - locket=1.0.0=py38h06a4308_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - matplotlib-inline=0.1.6=py38h06a4308_0
  - mistune=2.0.4=py38h06a4308_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.2.1=py38h807cd23_1
  - mkl_random=1.2.1=py38h807cd23_1
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - mpmath=1.3.0=py38h06a4308_0
  - nbclassic=0.5.5=py38h06a4308_0
  - nbclient=0.8.0=py38h06a4308_0
  - nbconvert=7.16.4=py38h06a4308_0
  - nbformat=5.10.4=py38h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py38h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - notebook-shim=0.2.3=py38h06a4308_0
  - numpy=1.24.4=py38h59b608b_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=24.1=py38h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.4.1=py38h06a4308_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=10.4.0=py38h5eee18b_0
  - pip=21.1.3=py38h06a4308_0
  - pkgutil-resolve-name=1.3.10=py38h06a4308_1
  - platformdirs=3.10.0=py38h06a4308_0
  - prometheus_client=0.14.1=py38h06a4308_0
  - prompt-toolkit=3.0.43=py38h06a4308_0
  - psutil=5.9.0=py38h5eee18b_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py38h06a4308_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.20=he870216_0
  - python-dateutil=2.9.0post0=py38h06a4308_2
  - python-fastjsonschema=2.16.2=py38h06a4308_0
  - python_abi=3.8=2_cp38
  - pytorch=2.4.1=py3.8_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py38h06a4308_0
  - pyyaml=6.0.2=py38h5eee18b_0
  - pyzmq=25.1.2=py38h6a678d5_0
  - readline=8.3=hc2a1206_0
  - referencing=0.30.2=py38h06a4308_0
  - requests=2.32.3=py38h06a4308_0
  - rpds-py=0.10.6=py38hb02cf49_0
  - send2trash=1.8.2=py38h06a4308_0
  - setuptools=75.1.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py38h06a4308_0
  - soupsieve=2.5=py38h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.13.3=py38h06a4308_0
  - terminado=0.17.1=py38h06a4308_0
  - tinycss2=1.2.1=py38h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - toolz=0.12.0=py38h06a4308_0
  - torchtriton=3.0.0=py38
  - tornado=6.4.1=py38h5eee18b_0
  - traitlets=5.14.3=py38h06a4308_0
  - typing_extensions=4.11.0=py38h06a4308_0
  - unicodedata2=15.1.0=py38h5eee18b_0
  - urllib3=2.2.3=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - websocket-client=1.8.0=py38h06a4308_0
  - wheel=0.44.0=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.20.2=py38h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - agentlace==0.1.3
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.8
      - blinker==1.8.2
      - cachetools==5.5.2
      - catkin-pkg==1.1.0
      - contextlib2==21.6.0
      - contourpy==1.1.1
      - distro==1.9.0
      - dm-control==1.0.23
      - dm-env==1.6
      - dm-tree==0.1.8
      - docutils==0.20.1
      - easyhid==0.0.10
      - einops==0.8.1
      - etils==1.3.0
      - eval-type-backport==0.3.1
      - evdev==1.9.2
      - farama-notifications==0.0.4
      - flask==3.0.3
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.10.0
      - google-auth==2.43.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - gymnasium==0.29.1
      - hf-xet==1.2.0
      - hidapi==0.15.0
      - huggingface-hub==0.36.0
      - hydra-core==1.1.0
      - hydra-submitit-launcher==1.1.5
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.4
      - inputs==0.5
      - ipdb==0.13.9
      - itsdangerous==2.2.0
      - joblib==1.4.2
      - labmaze==1.0.6
      - lxml==6.0.2
      - lz4==4.3.3
      - markdown==3.7
      - matplotlib==3.7.5
      - ml-collections==0.1.1
      - mujoco==2.3.7
      - natsort==8.4.0
      - oauthlib==3.3.1
      - omegaconf==2.1.2
      - opencv-python==4.12.0.88
      - pandas==1.3.0
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pymodbus==2.5.3
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pyrealsense2==2.55.1.6486
      - pyserial==3.5
      - pyspacemouse==1.1.5
      - python-xlib==0.33
      - requests-oauthlib==2.0.0
      - rospkg==1.6.1
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sentry-sdk==2.48.0
      - sklearn==0.0
      - smmap==5.0.2
      - submitit==1.5.3
      - tb-nightly==2.14.0a20230808
      - tensorboard-data-server==0.7.2
      - termcolor==1.1.0
      - threadpoolctl==3.5.0
      - timm==1.0.22
      - toml==0.10.2
      - torchaudio==2.4.1+cu124
      - torchvision==0.19.1+cu124
      - tqdm==4.67.1
      - typing==3.7.4.3
      - typing-extensions==4.13.2
      - wandb==0.23.1
      - werkzeug==3.0.6
      - yapf==0.31.0
      - zmq==0.0.0
prefix: /home/descfly/.conda/envs/hilserl-torch
